apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-cloudflare
  namespace: cloudflare
spec:
  encryptedData:
    api_key: AgAeR+EVJyzmrHNcE+NLBiJwRQcfA53kLPiy9WyO4k5gmn4KDiaGM2QwH2R9oShU45vnh4Nd7IIlH2orESp94jXaP2HvwsF7Qy3gLXMmCqrOL4lDFVJpdqSTtF9BH8jWW6OfSKZTt/pwP2ZM6Y5jsaKZSLeG9w6mC/dAJILxlElJJCq2B1xd5LYF6o0iSHmGamolKFSk7OIsba+BvSyFv4g34umxzCOfqD1yzLwoPLDoA4f1qg6973MERqq85AgQZ3rd8iXihlG0KZwPmxrymlixIn4xWmfO/oKslEWBx6ltpTdciIQAKYBNrHpAROjk+Z+P5pVtNFMhmPLQkPKDcASxFtdtWOs3KMLd4LSEWFbQyQAocxPl2DPOi0tdRiDUAtQOTe/UZ0jeSaSV12O2vQC9DqB0Ak6o3Cl2x9Ze7KwbY8GMRwRyfvjzqWimDvFIVlZjoALoyBJT5lx8tIdfC/gIjvUoSs6N4hoFl/sGdU9SAUmI/ioinLlck8KUNQYDyIZPwH2+wCLybmN/Dc232mfNzfcThzAO5mOb8iAHyHaak85QhtMSFK0AzawR0go8aBNVuBn2R7vW6g0vZjKFLvg68skFhvEEKaiGI/07DZqtX90O/H9JFL1RLYR3YhknPPay/tYDf6iHI9SefH1C5oisqYEEH0lC1VSoNL8wki0ns4qfIWe2MKF4zuvWaCLk60Vr3Me5Lsi71wzON9M19t1nhxVvvpzn8HCzUij9boCkO3Lsi3FChJKb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secret-cloudflare
      namespace: cloudflare

