apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: kube-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    chart: reflector
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: 6.1.47 
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
