proxyAddressForwarding: true

postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: "bn_keycloak_password"
    database: bitnami_keycloak


extraEnvVars:
- name: PROXY_ADDRESS_FORWARDING
  value: "true"

service:
  type: ClusterIP

# nodePorts:
#   http: "31391"
#   https: "31390"

ingress:
  enabled: true
  ingressClassName: ""
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: raelix-clusters.duckdns.org
  path: "/auth"
  tls: true 

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/cluster-issuer: letsencrypt-prod

auth:
  adminPassword: admin
  managementPassword: management

      # "defaultClientScopes": [
      #   "email",
      #   "groups",
      #   "profile",
      #   "roles",
      #   "web-origins"
      # ],
      # "optionalClientScopes": [
      #   "address",
      #   "microprofile-jwt",
      #   "offline_access",
      #   "phone"
      # ]

keycloakConfigCli:
  enabled: true
  configuration:
    realm.json: |
      {
        "realm": "master",
        "clientScopes": [
          {
            "name": "groups",
            "protocol": "openid-connect",
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          }
        ],
        "groups": [
          {
            "name": "oauth2-proxy"
          },
          {
            "name": "grafana-dev"
          },
          {
            "name": "grafana-admin"
          },
          {
            "name": "ArgoCDAdmins"
          },
          {
            "name": "ArgoCDViewers"
          }
        ],
        "clients": [
          {
            "clientId": "oauth2-proxy",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "oauth2-client-secret",
            "redirectUris": [
              "https://oauth2-proxy.raelix.tk:8443/oauth2/callback"
            ],
            "defaultClientScopes": [
              "email",
              "groups",
              "profile",
              "roles",
              "web-origins"
            ],
            "optionalClientScopes": [
              "address",
              "microprofile-jwt",
              "offline_access",
              "phone"
            ],
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          },
          {
            "clientId": "grafana",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "grafana-client-secret",
            "redirectUris": [
              "https://raelix-clusters.duckdns.org:8443/grafana/login/generic_oauth"
            ],
            "defaultClientScopes": [
              "email",
              "groups",
              "profile",
              "roles",
              "web-origins"
            ],
            "optionalClientScopes": [
              "address",
              "microprofile-jwt",
              "offline_access",
              "phone"
            ],
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          },
          {
            "clientId": "argocd",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "argocd-client-secret",
            "redirectUris": [
              "https://raelix-clusters.duckdns.org:8443/argocd/auth/callback"
            ],
            "defaultClientScopes": [
              "email",
              "groups",
              "profile",
              "roles",
              "web-origins"
            ],
            "optionalClientScopes": [
              "address",
              "microprofile-jwt",
              "offline_access",
              "phone"
            ],
            "protocolMappers": [
              {
                "name": "groups",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "config": {
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          }
        ],
        "users": [
          {
            "username": "user",
            "email": "user@domain.com",
            "enabled": true,
            "firstName": "userFirstName",
            "lastName": "userLastName",
            "groups": [
              "grafana-admin",
              "ArgoCDAdmins"
            ],
            "realmRoles": [
              "admin",
              "default-roles-master"
            ],
            "attributes": [
              {
                "locale": [
                  "it"
                ]
              }
            ]
          },
          {
            "username": "admin",
            "email": "admin@domain.com",
            "enabled": true,
            "firstName": "adminFirstName",
            "lastName": "adminLastName",
            "groups": [
              "grafana-admin",
              "ArgoCDAdmins",
              "oauth2-proxy"
            ],
            "credentials": [
              {
                "type": "password",
                "userLabel": "initial",
                "value": "admin"
              }
            ],
            "attributes": [
              {
                "locale": [
                  "it"
                ]
              }
            ]
          },
          {
            "username": "viewer",
            "email": "viewer@domain.com",
            "enabled": true,
            "firstName": "viewerFirstName",
            "lastName": "viewerLastName",
            "groups": [
              "grafana-dev",
              "ArgoCDViewers"
            ],
            "credentials": [
              {
                "type": "password",
                "userLabel": "initial",
                "value": "viewer"
              }
            ],
            "attributes": [
              {
                "locale": [
                  "it"
                ]
              }
            ]
          }
        ]
      }