apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-raelix-tk-cert-prod
  namespace: cert-manager
spec:
  secretName: home-raelix-tk-cert-prod
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: 'home.raelix.tk'
  dnsNames:
  - 'home.raelix.tk'