apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: raelix-com-cert-wild-card-certificate
  namespace: cert-manager
spec:
  secretName: raelix-com-cert-wild-card
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cloudflare-production
  commonName: '*.raelix.com'
  dnsNames:
  - '*.raelix.com'