apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: raelix-tk-cert-prod
  namespace: cert-manager
spec:
  secretName: raelix-tk-cert-prod
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: 'home.raelix.tk'
  dnsNames:
  - 'home.raelix.tk'