apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: cloudflare
  labels:
    app: cloudflare
spec:
  selector:
    matchLabels:
      app: cloudflare
  replicas: 1
  progressDeadlineSeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cloudflare
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: cloudflare
          image: oznu/cloudflare-ddns
          imagePullPolicy: IfNotPresent
          env:
            - name: PROXIED
              value: "false"
            - name: ZONE
              value: "raelix.com"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-cloudflare
                  key: api_key
            # - name: SUBDOMAINS
            #   value: "raelix-cluster,raelix-clusters,rancher-k8s"
          resources:
            requests:
              memory: 16Mi
              cpu: 50m
            limits:
              memory: 48Mi
              cpu: 150m