apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: kube-filter
  labels:
    logging: "true"
spec:
  match: kube.*
  filters:
  - kubernetes:
      # kubeURL: https://kubernetes.default.svc:443
      # kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      # kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      mergeLog: true
      keepLog: false
      labels: true
      annotations: false
      bufferSize: "128k"
  - nest:
      operation: lift
      nestedUnder: kubernetes
  - nest:
      operation: lift
      nestedUnder: labels
      addPrefix: labels_
  - modify:
      rules:
      - remove: stream
      - remove: pod_id
      - remove: host
      - remove: container_hash
      - rename: 
          pod_name: pod
          namespace_name: namespace
          container_name: container
          "labels_app.kubernetes.io/name": "deployment" 
          "labels_app.kubernetes.io/instance": "instance"
  - nest:
      operation: nest
      wildcard:
      - labels_*
      nestUnder: labels
      removePrefix: labels_
  - modify:
      rules:
      - remove: labels
  - rewriteTag:
      rules:
      - "$pod /(?i)(^ingress-nginx-controller*)/ ingress-nginx-controller.$TAG false"

