proxyAddressForwarding: true

extraEnvVars:
- name: PROXY_ADDRESS_FORWARDING
  value: "true"

service:
  type: ClusterIP

# nodePorts:
#   http: "31391"
#   https: "31390"

ingress:
  enabled: true
  ingressClassName: ""
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: raelix-cluster.duckdns.org
  path: "/auth"
  tls: true 

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/cluster-issuer: letsencrypt-prod