service:
  main:
    ports:
      http:
        port: 9117

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: false
    # existingClaim:  # your-claim
    # subPath:  # some-subpath
    # accessMode: ReadWriteOnce
    # size: 1Gi
    # retain: true

  torrentblackhole:
    enabled: false
    mountPath: /downloads

