service:
  main:
    ports:
      http:
        port: 9117

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: false
    # existingClaim:  # your-claim
    # subPath:  # some-subpath
    # storageClass: nfs-client
    # accessMode: ReadWriteOnce
    # size: 1Gi
    # retain: true

  torrentblackhole:
    enabled: false
    mountPath: /downloads

volumeClaimTemplates:
- name: jackett
  mountPath: /config
  accessMode: "ReadWriteOnce"
  storageClass: nfs-client
  size: 1Gi
# - name: backup
#   mountPath: /backup
#   subPath: theSubPath
#   accessMode: "ReadWriteOnce"
#   size: 2Gi
#   storageClass: cheap-storage-class

controller:
  enabled: true
  type: statefulset
