service:
  main:
    ports:
      http:
        port: 9117

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: true
    # existingClaim:  # your-claim
    # subPath:  # some-subpath
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true

  torrentblackhole:
    enabled: false
    mountPath: /downloads

