server:
  extraArgs:
   - --insecure
   - --rootpath
   - /

  rbacConfig:
    policy.csv: |
      g, ArgoCDAdmins, role:admin
      g, ArgoCDViewers, role:readonly

  ingress:
    enabled: true 
    labels: {}

    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      # cert-manager.io/cluster-issuer: letsencrypt-staging


    ## Argo Ingress.
    ## Hostnames must be provided if Ingress is enabled.
    ## Secrets must be manually created in the namespace
    ##
    hosts:
      - argocd.raelix.tk

    paths:
      - /
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.raelix.tk

  config:
    url: "https://argocd.raelix.tk:8443"
    # Argo CD instance label key
    application.instanceLabelKey: argocd.argoproj.io/instance

    # DEPRECATED: Please instead use configs.credentialTemplates and configs.repositories
    # repositories: |
    #   - url: git@github.com:group/repo.git
    #     sshPrivateKeySecret:
    #       name: secret-name
    #       key: sshPrivateKey
    #   - type: helm
    #     url: https://charts.helm.sh/stable
    #     name: stable
    #   - type: helm
    #     url: https://argoproj.github.io/argo-helm
    #     name: argo

    oidc.config: |
      name: Keycloak
      issuer: https://auth.raelix.tk:8443/auth/realms/master
      clientID: argocd
      clientSecret: argocd-client-secret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email

# redis-ha:
#   enabled: true

# controller:
#   enableStatefulSet: true

# server:
#   autoscaling:
#     enabled: true
#     minReplicas: 2

# repoServer:
#   autoscaling:
#     enabled: true
#     minReplicas: 2