apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdns
  namespace: duckdns
  labels:
    app: duckdns
spec:
  selector:
    matchLabels:
      app: duckdns
  replicas: 1
  progressDeadlineSeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: duckdns
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: duckdns
          image: linuxserver/duckdns:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-duckdns
                  key: token
            - name: SUBDOMAINS
              value: "raelix-cluster,raelix-clusters,rancher-k8s"
          resources:
            requests:
              memory: 16Mi
              cpu: 50m
            limits:
              memory: 48Mi
              cpu: 150m