apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-duckdns
  namespace: duckdns
spec:
  encryptedData:
    token: AgCXMfzW4PxOO+rXX76ySBN7MC2qrYMBU/PxWmTVF7bJYDL9OImV7IDVxPdRU3aMYVGj3lvoH3T+Np5NLnyrn1FgICl9z8OI1zl1ALO7HlgdMTkH1J9pGxf4pTgiUv/r7HK6B5Zud1IzvQwtVVe+FbV77BPDLFr2Knmd6QgTyUeerPISZUacxblh0ZFaobWYTfrabyUSChPEHjGoBX4p8Tx3qsDoZca9pwIDn+FuAq0r6S+w7iUsXP9mZIn+pmQV443nhxcpQeTuLPNGOJYOwCMEmhLAaMh+DB9mlKtKGyHyfy5XyJ8W7XZ/wJP7kJBVQdc/9lGuhcMzlNU3lTTbE5GaovwVYGma/dTTsWeUBvbHSVyvdufKvR4Y+RYQWNjuOGryGBFBwkJVGVcXGroS1FoDLcY+Py/29ycVJbyRO4jLEjO0JZSg/5+yO1vp5LSMEgM6wNcnq7Wlb/1nFHh4yJdPmdyD6ydpe6tjCJbZgsO+Vl5xyg6u3/Mz1K15VMDcMSW20lPPaIdYM+GKqMvFHsXgyVaJAhx6+8Fq72C5k99JFhb7WK7FLrZNnLNSY1kmKb4ezmnuAMA9w6viL5+gKWUflof9mFg9TdnKI8m3MSiFbshmaki6/oZzUY0Z+tQ+dAgff1LVhZ3fGnXbta6dbVD59p/9tD+rYrMNe2FAxTAzssEr1aYfQasS8jQGmwWJXXJu1aJGau85j5EA7CMos5dwbJigRGThym1I+Dbk3jITvNwKlAw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secret-duckdns
      namespace: duckdns

