apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: subdomains
  literals:
  - SUBDOMAINS=raelix,raelix-cluster,raelix-clusters,rancher-k8s
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../../components/duckdns
- duckdns-sealed-secret.yaml

patchesStrategicMerge:
- patch.yaml

namespace: duckdns