apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-auth
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgBOwk0SNnR/UI8gkTKBg3tR0zJfEmFup1mb/CH2ymQHJmiN+FyIXjpFP6vr/THD6yq41eVdoDEYawtFaMfgl6g5KcBrLCvZEO/hVH3XEwuKEECsS4ek/+dAGDBljz+VfK30yxcfovApNkAS8Cls0KAhdye1H8ajAz0szFDHql1l2tV5u0rda+SGCAoVCEQmSBGt9ExPSDjNuy9o1W9pT09U4dVX4oyF1lFI3f2EN79Zt9GQ+UfxxMHL3rVwFTsBdlfJEbKNrOfF9SjbZq255gPjD56Vg856/5NXcUROlbcdG34Dlu22kR/P8LQyPEPiL4U35GcOWlk9tNpZ5mgr3Hit2TCUrkkpaEDifC/juAEM7I93ZZvn3JxAnOViAGUFM4T3YTIJuBnW7y4V/pcwDVbRsPGYV1PkkCdjZNvfKgQmmB1ODtfmmXaP9IakQjMc6t9uc3uq6kLfgRqBkcmYM1lHJCEjJ75/+A3HcwgRSDVoYYqpsEBe4hBGV9bTtDNGvIHGNjCjU/9QAEeI3M4vBidn0F6NXnTXGN9lnzHqd8/a5FInCg1FeeUtlFFhy5rhTi4Xq96UZQXLV35KUlOQqk2oxYKVkeHY9X32EBJETJM/OjAm6RmoKkoIpsnbbb4cPOhLgDegYSZv3Qf3tcrXIUPc2CR81ylZZzDFDi/BauNboJBvElAbe/cukciVd1joWys3cwqvczb8t9A=
    management-password: AgAmCKycmAhbc9knjBxtl1SNLr+qta284W0h7tLoAdP2jjiaqOa79CUshGGE/HoC9jjyUvR+hEMJCIKW2lEML3Hs84iwRXEKK0oF9bbVpkROvEdcEtcnXyfp/oFN3Gmi+bz0hcMOtK8LIpGTZE7tTfi63AEyceLJD+aoM2OOgtSzZW/7ZC7Nksa1EzEnonJJzZdWSuyaLaR7I6jnxSdjSThyfDQh1QduoseU/K+tjRJevAbZYe3xDJYeU5yKaI/WbleUpG7eu0mLaK9l7pMdxCFQeVqBDHkSPXm80LZM5bkmxE7RuYo2x27Y1K7OycK8wJqaBggbx/b++V4ne5rxM+lTESmiKOJWJehZ1n/AKXKx0PHUzol8ZTWxhjmjCHGjQzbvqLoRS00/rZ9GleVysBF+92Lky4TUjWS1+NTh4PlQnjRbWAxwp/xDddbsOa6tr2/lAqBgD2tsWhKrU2ms9eQPn6V7wmC7eELoMvcze2mLk+l7W0g5fPMDbX3UbqFBjNvNhKIWtA7iF2d8NAc+PtEF5I/pVzru1Kuz55XoXAjVWJxR7I4scpVvk3sz4S4e0n4EhCzMfC4YMMiEMxHflrpRtHoo5y/civyezqgy9xQrAKn8+cgaCvn094fFpew3PopeA4TOfCMzJyzU9Gpq1ofz3l7SP+ntTnJRxwUsTyGCm514tkM04J4yX2EKag3CLdZ34tNOd5JTetF2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-auth
      namespace: keycloak
    type: Opaque
