apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak-ns.yaml
  - keycloak-auth-sealed.yaml
  - keycloak-postgres-auth-sealed.yaml
  - servicemonitor-keycloak.yaml
  - app-keycloak.yaml