apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-metrics
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /auth/realms/master/metrics
  namespaceSelector:
    matchNames:
    - keycloak
  selector:
    matchLabels:
      app.kubernetes.io/component: keycloak
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
