apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgAGOmYv8LheQ3boI7cH/cxIMOJGP58Z80oOcjQNuxAhPb64FWRC7KKqIyWdNBW5r8WgD3yAozUz6P0Zw2SEJxUHMud4G7rczvmOu61FdwuAx9Rn4PGmEd/KsiJDWLivn+OBtAms9Iwu+zkbKVm30tA60K6vchMkXHpDxWBBA1LwJr4E4pWz4DM9H0iy8Lfgmi1+qDK5os9YRHNIxVw270WRQxtC0IePjSAgnE+O0HPhK9w5WINOnKdDe2dxbz17X9/YUb9s6Io9/tdCTpI1yTBOrIYv6ULV7Hoc5ibZgngrFU9XI9YAN28iSzu5KyPBG2T/fhRbnphNqpfldidCq5XaFnSjtLYmMVe480MBtK1cGl8G039e1+YPHL82Dxif2uTV5SmKtRqIaVN4j1kRvDQ5RVKamAUynHJBPvKUMpPV1EXbM+dJJRhem5yaeWKot77vfo+WgcuEZf137H8a/FsIyfe7xOxKaqPR/TW8f+sjOT5fOmyCU0b7SYNLGiBI5agsDEk7d8Qusfz4rEyBgCS98Hr1eJRo3382jUZ1P+dWz7iaiCboy0QesJCkh13vNF3vEec/zc9uVL+v1u917zWlhv84W6tusutSiFr1R2iauf/NdVXYz0EWmRZEgdOPuSrpPEkekVyTLQxuDcsyS0UjiM3lzdSs73+DNpS+K8Qv0sCSGDgMJ3UHOczZYlREFdPGDdunnAOxuCYjkDCaoT2fctf2nYaf7ek74nR7YFOn8XbVx7P2
    api-token: AgCAl7EhbeHntOBwGm4LfLKixMpejoOyX5uYOkhQIgbaB4OE12FFywwEypHA8CSZ2wK68moq0TXSxFz6R19uwL0gdKcBFb1QxDcGo7mdXbxqM63E+JEOouujAS7hD1WorlL2tuBekSi+ymfRYFnaQy31Vp5dmmPJrCSJCeotAIaxA9S7Twagb4N5EtO4dm2c5aFiOFjoNCiRRh54/36I9v3gn72kfvlLuNOQ6wA8v/p37qINWn8W5VSviGpXLqzuexuXXr/+tvmjoo2PtUzA+p67LsZv7zM9oJdvRlhf7FzDxja8/cVBGQtTWbTVv2WPSEo09GYttTYrqH+rl2H+SsFsYqJom9LZ9sbd4qbbRXE/gN1AD5+QqURWN5+NwMOP3SfXtIj5iSqA/UFoZmwSWEK71LEEcxA+jFRihEW66CoKgBJSCT+AILZk8YahylZTgThqv0rsH1hXydRlYbTC4eXGS24jR2TLsrFMeNLpgzOF/qIIltwVhK1bgK1jFFOIWxayKhpYM7l3eO5WZC4nL1huAKQmjQXpwBmpg1g7IiZz6BZbvnGplf2/Am/jJG0OPWqmLMOAKSkQEwuuscuntQ2hINh5KnTfFynCk4CxupnSH7Lmy8bbERJ1rFfD+hKAoPolqtuArvK9fqMAKLfeJpBtigTa/vpVpCrFYH7VjL8BpCDH3mFz12INEgTHfjtH9IbwjPIZPu8TEoXr0B7QlWKz723OZn9dJR7jn5xiTLmuCcdO1vWmsnd0
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

