apiVersion: v1
kind: PersistentVolume
metadata:
  name: gdrive-volume
  labels:
    name: gdrive-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: rclone
  csi:
    driver: csi-rclone
    volumeHandle: data-id
