apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gdrive-volume
  namespace: paperless
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rclone
  selector:
    matchLabels:
      name: gdrive-volume
