ingress:
  main:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.raelix.tk:8443/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.raelix.tk:8443/oauth2/start"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
      ingress.kubernetes.io/force-ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "1024m"
      nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
      # kubernetes.io/ingress.allow-http: "false"
      # nginx.ingress.kubernetes.io/rewrite-target: /$1
      # nginx.ingress.kubernetes.io/configuration-snippet: |
      #   proxy_set_header   Host $host;
      #   proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      #   proxy_set_header   X-Forwarded-Host $host;
      #   proxy_set_header   X-Forwarded-Proto $scheme;
    enabled: true
    hosts:
    - host: radarr.raelix.tk
      paths:
      - path: /
    tls:
    - secretName: radarr-raelix-tk
      hosts:
      - radarr.raelix.tk
