grafana:

  service:
    portName: http-web
    type: ClusterIP

  persistence:
    type: pvc
    enabled: true
    # storageClassName: default
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection

  # datasources:
  #   datasources.yaml:
  #     apiVersion: 1
  #     # -- Datasources list. Each Datasource type has specific configurations.
  #     datasources:
  #     - name: Prometheus
  #       type: prometheus
  #       url: http://prometheus-kube-prometheus-prometheus:9090
  #       access: proxy
  #       isDefault: true


  grafana.ini:
    server:
      root_url: https://raelix-cluster.duckdns.org:8443/grafana
      serve_from_sub_path: "true"
    auth.basic:
      enabled: false
    auth:
      disable_login_form: true
      # signout_redirect_url: https://raelix-cluster.duckdns.org:8443/auth/realms/master/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fraelix-cluster.duckdns.org%3A8443%2Fgrafana%2Flogout
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      scopes: profile,email,groups
      auth_url: https://raelix-cluster.duckdns.org:8443/auth/realms/master/protocol/openid-connect/auth
      token_url: https://raelix-cluster.duckdns.org:8443/auth/realms/master/protocol/openid-connect/token
      api_url: https://raelix-cluster.duckdns.org:8443/auth/realms/master/protocol/openid-connect/userinfo
      client_id: grafana
      client_secret: grafana-client-secret
      role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'

  enabled: true
  namespaceOverride: ""

  defaultDashboardsEnabled: true

  defaultDashboardsTimezone: utc

  adminPassword: prom-operator

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - raelix-cluster.duckdns.org
      
    path: /grafana

    tls: 
    - secretName: prometheus-grafana-cert
      hosts:
      - raelix-cluster.duckdns.org

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'homeassistant'
        orgId: 1
        folder: 'Home Assistant Dashboard'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /tmp/dashboards/homeassistant
      - name: 'opensea-dashboard'
        orgId: 1
        folder: 'Opensea Dashboard'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /tmp/dashboards/opensea-dashboard


prometheus:

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

    additionalScrapeConfigs: 
    
    - job_name: 'homeassistant'
      scrape_interval: 15s
      honor_labels: true
      metrics_path: '/federate'

      params:
        'match[]':
          - '{job="home-assistant"}'
      static_configs:
      - targets: ['192.168.1.100:9090']