apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: kube-tail
  labels:
    logging: "true"
spec:
  tail:
    tag: kube.*
    # path: /var/log/containers/*.log
    path: /var/log/containers/ingress-nginx-controller*.log
    parser: docker
    refreshIntervalSeconds: 10
    memBufLimit: 50MB
    skipLongLines: true
